@startuml

!theme spacelab

object lastUpdatedGBufferClearingNode{
    Buffer Cleaning Node
}

package worldRenderingNodes{
    diamond worldRenderingNodes
    object opaqueObjectNode
    object opaqueBlockNode
    object alphaRejectNode
    object overlayNode
    lastUpdatedGBufferClearingNode -> worldRenderingNodes
    worldRenderingNodes -> opaqueBlockNode
    worldRenderingNodes -> opaqueObjectNode
    worldRenderingNodes -> alphaRejectNode
    worldRenderingNodes -> overlayNode
}

@enduml